name: Hello World

on:
  push:
    branches: 
    - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
    - name: Hello world step
      run: echo "Hello, world!"
  date_job:
    runs-on: ubuntu-latest
    steps:
    - name: Second job stepa
      run: date
  dir_listing_job:
    runs-on: ubuntu-latest
    steps:
    - name: Third job step
      run: ls -la